dist: trusty
sudo: required
language: clojure
before_install:
  - test/install_deps.sh
  - test/start_mesos.sh
script:
  - make check
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
  #- openjdk8
notifications:
  email:
      - oubiwann@gmail.com
