dist: trusty
sudo: required
language: clojure
before_script:
  - bash test/install_deps.sh
  - bash test/start_mesos.sh
script:
  - make check
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
  #- openjdk8
notifications:
  email:
      - oubiwann@gmail.com
