dist: trusty
sudo: required
language: clojure
before_script:
  - bash test/install_deps.sh
  - bash test/start_mesos.sh
script:
  - make travis-check
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk6
  #- openjdk7
 
notifications:
  email:
      - oubiwann@gmail.com
